apiVersion: v1
kind: Service
metadata:
  name: awesomego-service
  #namespace: apple
spec:
  selector:
    tier: backendapi
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: ext
      port: 5000
      #port inside container
      targetPort: 8080